**Tensor DataType Declaration:**

In [ ]:
import tensorflow as tf

string = tf.Variable("My name is Shruti Gurung", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.14, tf.float64)

print(string)
print(number)
print(floating)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'My name is Shruti Gurung'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>


**Rank/Degree of Tensor**

In [ ]:
rank1_tensor = tf.Variable(["Shruti", "Gurung"], tf.string)
rank2_tensor = tf.Variable([["Shruti", "a","b"], ["Gurung", "b","c"], ["Sushma", "C","d"]],tf.string )

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of Tensor**

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

**Changing Shape**

In [ ]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [ ]:
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [ ]:
tensor3 = tf.reshape(tensor2, [3,-1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
with tf.Session() as sess:
  tensor1.eval()
#

2.17.1
